In [10]:
#Imports packages
import pandas as pd
import numpy as np

In [11]:
#Reads data
indicators = pd.read_csv('../data/processed/technical_indicators.csv')
#Slices data
indicators = indicators.iloc[:, 1:]
#Names columns
indicators.columns = [
    'Date', 
    'Open', 
    'High', 
    'Low', 
    'Close', 
    'Volume', 
    'RSI', 
    'Stochastic Oscillator', 
    'SMAs',
    'SMAm', 
    'MACD', 
    'A/D'
    ]
indicators.head()

,Date,Open,High,Low,Close,Volume,RSI,Stochastic Oscillator,SMAs,SMAm,MACD,A/D
0,2019-03-01,2339.97,2349.46,2330.85,2333.11,20112068.0,NaN,NaN,NaN,NaN,NaN,-1.522725e+07
1,2019-03-04,2341.55,2349.08,2321.71,2328.05,25995529.0,NaN,NaN,NaN,NaN,NaN,-2.917954e+07
2,2019-03-05,2325.80,2338.74,2318.81,2321.32,15909279.0,NaN,NaN,NaN,NaN,NaN,-4.108157e+07
3,2019-03-06,2325.09,2329.40,2317.00,2327.16,20220415.0,NaN,NaN,NaN,NaN,NaN,-2.816659e+07
4,2019-03-07,2326.78,2335.46,2305.25,2308.48,16175290.0,NaN,NaN,NaN,NaN,NaN,-4.088301e+07

In [12]:
#Ceates a column with additional metric 'Target'
indicators['Target'] = indicators['Close']-indicators.Open
indicators['Target'] = indicators['Target'].shift(-1)

#Ceates a column with binary metric 'TargetClass'
indicators['TargetClass'] = [1 if indicators.Target[i]>0 else 0 for i in range(len(indicators))]
#Ceates a column with additional metric 'TargetNextClose'
indicators['TargetNextClose'] = indicators['Close'].shift(-1)
#Drops missing data
indicators.dropna(inplace=True)

indicators.head()

,Date,Open,High,Low,Close,Volume,RSI,Stochastic Oscillator,SMAs,SMAm,MACD,A/D,Target,TargetClass,TargetNextClose
49,2019-05-15,2176.30,2181.49,2152.99,2169.18,29226451.0,23.646986,7.183742,2267.704286,2322.5444,-19.002922,-1.163134e+08,14.33,1,2188.43
50,2019-05-16,2174.10,2193.89,2162.46,2188.43,21947998.0,29.838080,15.725252,2254.568571,2319.6508,-15.223228,-1.019910e+08,-2.83,0,2184.35
51,2019-05-17,2187.18,2187.18,2165.97,2184.35,19175312.0,29.295877,13.914896,2242.110714,2316.7768,-12.013150,-8.793269e+07,-11.46,0,2175.51
52,2019-05-20,2186.97,2189.10,2159.78,2175.51,19882122.0,28.104252,9.992457,2228.057857,2313.8606,-9.604766,-8.648154e+07,12.01,1,2190.93
53,2019-05-21,2178.92,2191.28,2173.74,2190.93,22502583.0,33.207839,18.304627,2215.404286,2311.1360,-6.255012,-6.487701e+07,20.58,1,2214.36

In [13]:
#Reads data
sentiment = pd.read_csv('../data/processed/sentiment.csv')
#Slices data
sentiment = sentiment.iloc[:, 1:]
#Reames column
sentiment.rename(columns={'date': 'Date'}, inplace=True)
sentiment.head()

,Date,text,sentiment_score_2_fold,sentiment_score_3_fold,sentiment_score_SO_PMI
0,2024-08-30,['Ostatnia sesja miesiąca potwierdziła silne p...,1.0,0.0,1.98
1,2024-08-30,['Ostatni tydzień wakacji na rynkach finansowy...,1.0,0.0,1.99
2,2024-08-28,['Środkowa sesja tygodnia zakończyła się spadk...,1.0,0.0,2.73
3,2024-08-27,['Nerwowa sesja na GPW zakończyła się ostatecz...,0.0,-1.0,0.74
4,2024-08-23,['Mijający tydzień obfitował w dane makro z po...,1.0,0.0,1.98

In [14]:
#Sets a timespan of 1y
indicators_1y = indicators[(indicators['Date'] >= '2023-06-01') & (indicators['Date'] <= '2024-08-30')]
#Changes index to date
indicators_1y.set_index('Date', inplace=True)
indicators_1y.head()

,Open,High,Low,Close,Volume,RSI,Stochastic Oscillator,SMAs,SMAm,MACD,A/D,Target,TargetClass,TargetNextClose
Date,,,,,,,,,,,,,,
2023-06-01,1902.02,1949.50,1902.02,1946.21,14941664.0,52.753971,41.230001,1958.207143,1864.9542,-8.800798,6.200048e+07,58.86,1,2018.09
2023-06-02,1959.23,2018.09,1959.23,2018.09,19817090.0,61.483312,93.982093,1963.740000,1871.5848,-3.730023,8.181757e+07,0.37,1,2020.07
2023-06-05,2019.70,2053.48,2010.92,2020.07,15886416.0,61.693270,79.559498,1968.828571,1877.6030,-0.470914,7.276202e+07,35.61,1,2053.44
2023-06-06,2017.83,2060.37,2016.18,2053.44,25672961.0,65.142022,95.931666,1977.425714,1884.5260,3.486139,9.038277e+07,-16.23,0,2036.31
2023-06-07,2052.54,2055.49,2027.06,2036.31,16027064.0,62.053580,85.875308,1984.312143,1891.1340,4.442477,8.478485e+07,4.85,1,2050.99

In [15]:
#Saves dataset
indicators_1y.to_csv('../data/processed/dataset_1y.csv')

In [16]:
#Sets a timespan of 5y
indicators_5y = indicators[(indicators['Date'] >= '2019-06-01') & (indicators['Date'] <= '2024-08-30')]
#Changes index to date
indicators_5y.set_index('Date', inplace=True)
indicators_5y.head()

,Open,High,Low,Close,Volume,RSI,Stochastic Oscillator,SMAs,SMAm,MACD,A/D,Target,TargetClass,TargetNextClose
Date,,,,,,,,,,,,,,
2019-06-03,2239.12,2248.09,2227.89,2237.71,15759707.0,50.928939,89.085174,2196.615000,2290.0932,11.193166,-1.553429e+07,-3.99,0,2233.75
2019-06-04,2237.74,2242.52,2222.32,2233.75,18733701.0,49.933507,83.761748,2201.227143,2287.7316,11.581539,-1.306738e+07,-13.96,0,2223.27
2019-06-05,2237.23,2242.22,2219.94,2223.27,27022940.0,47.298709,71.894463,2203.715714,2285.0166,10.812416,-3.201255e+07,36.74,1,2260.94
2019-06-06,2224.20,2272.07,2222.81,2260.94,43220594.0,56.237457,90.088165,2209.186429,2283.8534,12.406293,-8.322819e+06,20.08,1,2280.60
2019-06-07,2260.52,2287.39,2260.52,2280.60,23636701.0,60.046236,94.567565,2216.692857,2283.2096,14.220066,3.367980e+06,-7.89,0,2282.51

In [17]:
#Saves dataset
indicators_5y.to_csv('../data/processed/dataset_5y.csv')

In [18]:
#Merges datasets on date if in both columns
indicators_merged = pd.merge(indicators, sentiment, on='Date', how='inner')
#Changes index to date
indicators_merged.set_index('Date', inplace=True)
#Drops column text
indicators_merged = indicators_merged.drop(columns=['text'])

#Renames columns
indicators_merged.rename(columns=
    {
    'sentiment_score_2_fold': 'Binary', 
    'sentiment_score_3_fold': 'Neutral',
    'sentiment_score_SO_PMI': 'SO_PMI'
    }, 
    inplace=True)
columns = [
    'Open', 
    'High', 
    'Low', 
    'Close', 
    'Volume', 
    'RSI', 
    'Stochastic Oscillator', 
    'SMAs',
    'SMAm', 
    'MACD', 
    'A/D',
    'Binary', 
    'Neutral', 
    'SO_PMI',
    'Target', 
    'TargetClass', 
    'TargetNextClose'
]
indicators_merged = indicators_merged[columns]

indicators_merged.head()

,Open,High,Low,Close,Volume,RSI,Stochastic Oscillator,SMAs,SMAm,MACD,A/D,Binary,Neutral,SO_PMI,Target,TargetClass,TargetNextClose
Date,,,,,,,,,,,,,,,,,
2023-06-20,2081.84,2090.88,2063.37,2066.78,11658122.0,59.698478,73.340249,2037.184286,1945.5332,3.360979,4.833006e+07,1.0,1.0,1.36,8.92,1,2076.16
2023-06-23,2068.39,2073.39,2033.22,2035.00,11974508.0,52.905105,20.048289,2060.605000,1963.3766,-3.706225,4.269251e+07,1.0,0.0,1.52,34.18,1,2068.49
2023-06-26,2034.31,2075.63,2028.62,2068.49,9720902.0,57.766651,45.546365,2064.063571,1968.4208,-4.172880,4.946054e+07,1.0,0.0,2.46,-32.32,0,2039.34
2023-06-27,2071.66,2081.36,2025.49,2039.34,12003788.0,52.670138,15.524231,2063.056429,1972.3922,-6.447328,4.340816e+07,0.0,-1.0,1.08,-3.41,0,2045.15
2023-06-28,2048.56,2066.79,2029.44,2045.15,12607948.0,53.549780,20.877096,2063.687857,1976.2098,-7.489874,4.140641e+07,0.0,0.0,0.01,11.95,1,2062.11

In [19]:
#Creates 3 different datasets with a single sentiment metric each
indicators_binary = indicators_merged.drop(columns=['Neutral', 'SO_PMI'])
indicators_neutral = indicators_merged.drop(columns=['Binary', 'SO_PMI'])
indicators_so_pmi = indicators_merged.drop(columns=['Binary', 'Neutral'])

In [22]:
#Saves datasets
indicators_binary.to_csv('../data/processed/dataset_binary.csv')
indicators_neutral.to_csv('../data/processed/dataset_neutral.csv')
indicators_so_pmi.to_csv('../data/processed/dataset_so_pmi.csv')